sudo: required
language: c
compiler:
        - clang
        - gcc
before_install:
        - sudo apt-get update
        - sudo apt-get install python3
script:
        - ./travis.sh
os:
        - linux
        - os
